import { ReactNode } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import expedia from '../public/expedia-logo.svg';
import Head from 'next/head';

type Props = {
  children?: ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <div>
      <Head>
        <title>My Expedia</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='h-20 p-8 border-b border-solid bg-white'>
        <div className='flex justify-between'>
          <Link href='/'>
            <a>
              <Image alt='expedia logo' src={expedia} width={126} height={28} />
            </a>
          </Link>
        </div>
      </header>
      {children}
    </div>
  );
};

export default Layout;
